### PR TITLE
The update password form DOES show error messages

### PR DESCRIPTION
**Pull request by ttop34**
completed

### CODE REVIEW

**Comment by MontealegreLuis** [comment]
It needs one more validation. It shouldn't let me save an empty password

**Comment by ttop34** [comment]
now no blank passwords can be saved

**Review by MontealegreLuis — COMMENTED** [review]
Thank you!

**Comment by MontealegreLuis** [comment]
I now understand what you did I think you created the other branch based off of this one. That's why the other PR looks like having many changes. In these cases it's better to create new branches from master. Thank you!

**Pull request merged**
